In [1]:
#importing package as np

import numpy as np

In [139]:
#version of numpy

import numpy as np

np.version.version

'1.14.3'

In [16]:
#creating null vector of size 10

import numpy as np

arr = np.zeros(10)

print(arr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
#memory size of an array

import numpy as np

arr = np.arange((1000))

print(arr.size * arr.itemsize)

4000


In [43]:
#creating vector of size 10 and changing 5th value

import numpy as np

arr = np.zeros(10)

print(arr)

print("changing 5th value to 1")

arr[5] = 1

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
changing 5th value to 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [55]:
#creating a vector ranging from 10 to 49

import numpy as np

arr = np.arange(10,49)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [61]:
#reverse a vector

import numpy as np

arr = np.array([10,5,3,8,9,7,14,22])

print(arr)

#sorting an array

print("sorted array")

sorted_array = np.sort(arr)

print(sorted_array)

#to reverse

print("reverse array is:")

rev_array = sorted_array[::-1]

print(rev_array)

[10  5  3  8  9  7 14 22]
sorted array
[ 3  5  7  8  9 10 14 22]
reverse array is:
[22 14 10  9  8  7  5  3]


In [89]:
#creating 3x3 matrix

import numpy as np

arr = np.arange(9).reshape(3,3)

print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
#finding indeces of non-zero elements

import numpy as np

arr = np.array([1,2,0,0,4,0])

#non-zero
print(np.nonzero(arr))

#non-zero
print(np.flatnonzero(arr))

(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [78]:
#creating identity matrix

import numpy as np

#floating values

arr = np.identity(3,dtype = 'float32')

print("for floating values")

print(arr)

print("\n")

#Integers

print("for integer values")

print(np.identity(3,dtype='int32'))

for floating values
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


for integer values
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [154]:
#creating 3x3x3 matrix with random values

import numpy as np

arr = np.random.rand(3,3,3)

print(arr)



[[[0.68097733 0.95334388 0.76737846]
  [0.81726069 0.99991281 0.1533341 ]
  [0.3506153  0.47795582 0.73822024]]

 [[0.77888765 0.12755266 0.68043836]
  [0.03606803 0.4525664  0.62994087]
  [0.90137805 0.55867771 0.35436058]]

 [[0.19792164 0.89178266 0.54541603]
  [0.57764257 0.375767   0.65565621]
  [0.94531868 0.08313199 0.42096816]]]


In [235]:
#creating 10x10 array and finding max value

import numpy as np

arr = np.random.rand(10,10)

print(arr)
#max value
print("max value is:")

print(np.max(arr))

#min value
print("min value is:")

print(np.min(arr))

[[0.54830932 0.17166881 0.98982324 0.97391759 0.84901771 0.48685344
  0.74180586 0.08848059 0.92225361 0.67784903]
 [0.47605662 0.18283506 0.11997043 0.31356766 0.26055286 0.14397782
  0.8492945  0.4657247  0.74672626 0.29775397]
 [0.93224675 0.62865397 0.90893253 0.12526688 0.42126486 0.6780412
  0.80247006 0.7338101  0.61253477 0.79010695]
 [0.08319043 0.58883896 0.46613139 0.95274526 0.16857763 0.44928417
  0.91329934 0.87450467 0.8143669  0.90319358]
 [0.05770592 0.63353774 0.92463105 0.7297146  0.97459962 0.46581613
  0.53531732 0.40690531 0.51377778 0.64972804]
 [0.05634672 0.72916259 0.01359446 0.13211669 0.16812107 0.26955749
  0.34330066 0.90785234 0.74135249 0.60645357]
 [0.93971548 0.5694871  0.01624902 0.66541104 0.37176553 0.22322846
  0.65898024 0.51035004 0.40498746 0.71857072]
 [0.92919693 0.84686165 0.17865637 0.79459602 0.8318219  0.57483582
  0.80335174 0.02974489 0.83211313 0.89028576]
 [0.68708942 0.45659725 0.47922961 0.33241212 0.27348725 0.17810871
  0.65516552 

In [236]:
#creating random vector of size 30 and finding the mean value

import numpy as np

arr = np.random.randint(0,30,size=(30,30))

print(arr)

print("mean is:")

print(np.mean(arr))

[[15 17 13 13 16  3  7  6 12  5  6 18  4  5 21 19 11 14 24  1 28 27 27  7
  20  9 24 15  4 13]
 [15  9 13 28  7 16  2 12  5 29 13 15 27 25  5 22  4 23 11 15 16 11  8  7
   4 29 18 24 19  2]
 [ 5  1  9 10  6 21 20 29  7 20  3  4  5 14  6  5 22  9 13 14  3 26 21 20
  15 22 11  6 21 19]
 [ 2 16 12  5 23  4 23 27 13  8 23 24 27  9  9 25  2 19 28 12  1 28 29 27
   8 27 29 15 21 27]
 [ 3 27 26 20 20 16 28  8 29 13  4 29 11 11 23 24 24 16 12  3 14 23 19  3
  21  8 16  9  9 28]
 [22 14 18 28  5 27 12 16 24 29  8 21 12 28 14 10 23 22  1 20 17 29 15 26
  20 12  4 25 29 22]
 [10 28 21 12 17 26 19  0 14 15 15  1 27 12 17  8  5 22 22 12 17  9  3 16
   6 11 27  4  1 20]
 [ 5 20 29 23  8 19 12 22  8  4  8  9  3 23  8 15 14  9 23 25 17 10  5 17
  22  6  3  7 22 25]
 [28 21 17 12  4 26  5 24 21 20 20 27  7  3 24  4 23  5 11 14  1  5 22 28
   0 25  2 25 25  5]
 [ 4 17  1  4  7 11 27 24 12 14 20 12  2 24  8 29  1  4 16 10 26  4 21 11
   3  2  9 21 16 12]
 [ 4  6 15 11  9 22 11 14 25 13 11 16 18 16 16  3 

In [237]:
#2. How to get the documentation of numpy

import numpy as np

print(np.lookfor('add'))


Search results for 'add'
------------------------
numpy.add
    Add arguments element-wise.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.add_newdoc
    Adds documentation to obj which is in module place.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.add
    Add arguments element-wise.
numpy.add_docstring
    Add a docstring to a built-in obj if possible.
numpy.deprecate
    Issues a DeprecationWarning, adds warning to `old_name`'s
numpy.add_newdoc_ufunc
    Replace the docstring for a ufunc with new_docstring.
numpy.binary_repr
    Return the binary representation of the input number as a string.
numpy.ma.ids
    ids(self)
numpy.ma.append
    Append values to the end of an array.
numpy.bytes0.ljust
    Return B left justified in a string of length width. Padding is
numpy.bytes0.rjust
    Return B right justified in a string of length width. Padding is
numpy.bytes0.center
    Return B centered in a stri

In [238]:
# 15. constructing 2D array 1 on the border and 0 inside

import numpy as np

arr = np.ones((3,3))

print(arr)

print("final array is:")

arr[1:-1, 1:-1] = 0

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
final array is:
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [239]:
#filling border with 0's

import numpy as np

arr = np.zeros((5,5))

arr[1:-1, 1:-1] = 1

print("array is:")

print(arr)

print("\n")

arr = np.ones((5,5))
print(arr)

print("final array is:")
np.pad(arr, pad_width=1, mode = 'constant' ,constant_values = 0)

array is:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
final array is:


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [240]:
# 17

import numpy as np

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [229]:
# 18

import numpy as np

arr = np.random.randint(1,5,size=(5,5))

print(arr)

print("final array is:")
res = np.tril(arr,k=-1)
print(res)



[[3 3 3 2 2]
 [3 3 1 2 1]
 [4 4 4 3 4]
 [4 4 2 3 1]
 [1 3 1 4 1]]
final array is:
[[0 0 0 0 0]
 [3 0 0 0 0]
 [4 4 0 0 0]
 [4 4 2 0 0]
 [1 3 1 4 0]]


In [233]:
# 19

import numpy as np

Z = np.zeros((8,8),dtype=int)

Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [245]:
# 20

#numpy.unravel_index(indices,dims,order = 'C')

import numpy as np

np.unravel_index(100,(6,7,8))



(1, 5, 4)

In [252]:
# 21

import numpy as np

arr = np.tile(np.array([[0,1],[1,0]]),(4,4))

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [257]:
# 22

import numpy as np

arr = np.random.random((5,5))

print(arr)


arrmin,arrmax = arr.min(),arr.max()

print ("afer normalization")

arr = (arr - arrmin)/(arrmax - arrmin)

print(arr)


[[0.10706294 0.02683017 0.45809063 0.41844379 0.77010124]
 [0.89412244 0.41873349 0.51498079 0.64843525 0.26933002]
 [0.50843482 0.27486358 0.7138891  0.12421485 0.99057311]
 [0.43994121 0.65443518 0.41777887 0.06467095 0.26559006]
 [0.75269749 0.27687132 0.60412582 0.35490269 0.53907131]]
afer normalization
[[0.08325121 0.         0.44748494 0.40634655 0.77123374]
 [0.89992074 0.40664714 0.50651538 0.64499054 0.25162296]
 [0.49972314 0.2573647  0.71290683 0.10104839 1.        ]
 [0.42865273 0.65121619 0.40565661 0.03926439 0.24774229]
 [0.75317524 0.25944797 0.59901414 0.34041497 0.53151221]]


In [261]:
# 23

import numpy as np

np.dtype([("r", np.ubyte,1),("g",np.ubyte,1)])


dtype([('r', 'u1'), ('g', 'u1')])

In [265]:
# 24

import numpy as np

a=np.arange(15).reshape(5,3)

print(a)

b = np.arange(6).reshape(3,2)

print(b)

print("multiplied matrix is:")

print(np.dot(a,b))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
multiplied matrix is:
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [267]:
# 25

import numpy as np

arr = np.arange(11)

arr[3:8]=-arr[3:8]

print(arr)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [269]:
# 26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [275]:
# 27

import numpy as np

z= np.random.random(3)
print(z)

print(z**z)






[0.57537275 0.2175712  0.90472332]
[0.72758102 0.71759787 0.91339539]


In [277]:
# 28
import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


In [285]:
# 29

import numpy as np

arr = np.random.rand(3,3)
z=np.floor(arr)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [291]:
# 30

import numpy as np

z = np.arange(10).reshape(5,2)
print(z)

y = np. arange(6,16).reshape(2,5)
print(y)

print("interesect elements")
print(np.intersect1d(z,y))



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
interesect elements
[6 7 8 9]
