In [10]:
import numpy as np

a=np.arange(6).reshape(3,2)
print(a)
print("\n")
b=a.reshape(2,3)
print("modified array is:",b)

[[0 1]
 [2 3]
 [4 5]]


modified array is: [[0 1 2]
 [3 4 5]]


In [16]:
import numpy as np

a=np.arange(6).reshape(3,2)
print(a)
print("\n")
a.flatten()

[[0 1]
 [2 3]
 [4 5]]




array([0, 1, 2, 3, 4, 5])

In [24]:
import numpy as np

a=np.arange(6,12).reshape(3,2)
print(a)
print("\n")
#returns the corresponding element with in the index
a.flat[5]

[[ 6  7]
 [ 8  9]
 [10 11]]




11

In [28]:
import numpy as np

a=np.arange(6).reshape(3,2)
print(a)
print("\n")

#prints array as 1-D
a.ravel(order = 'F')

[[0 1]
 [2 3]
 [4 5]]




array([0, 2, 4, 1, 3, 5])

In [34]:
import numpy as np

a=np.arange(6).reshape(3,2)
print(a)
print("\n")

print("transpose")
print(a.transpose())



[[0 1]
 [2 3]
 [4 5]]


transpose
[[0 2 4]
 [1 3 5]]


In [46]:
import numpy as np

a=np.arange(27).reshape(3,3,3)
print(a)
print("\n")

print(np.swapaxes(a,2,1))


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[[ 0  3  6]
  [ 1  4  7]
  [ 2  5  8]]

 [[ 9 12 15]
  [10 13 16]
  [11 14 17]]

 [[18 21 24]
  [19 22 25]
  [20 23 26]]]
