In [1]:
#Data Types in numpy

import numpy as md

val = md.dtype('i1')

print(val)

#or

import numpy as md

val = md.dtype(md.int8)

print(val)

#Applying datatype to array

import numpy as md

dt = md.dtype([('val', md.int8)])
value = md.array([10,20,30], dtype=dt)

print(value)

print(value['val'])

#using String, Integer and Float datatypes

import numpy as md

dt = md.dtype([('name', 'S20'), ('Reg','i1'), ('marks', 'f4')])

value=md.array([('divya', 1, 25), ('sri', 2, 30)], dtype=dt)

print(value)

int8
int8
[(10,) (20,) (30,)]
[10 20 30]
[(b'divya', 1, 25.) (b'sri', 2, 30.)]


In [25]:
import numpy as np

a = np.array([[1.5,2,3,4],[4,5,6,7],[8,0,9,1]],dtype = 'float')

print(a)

print(a.dtype)

print(a.itemsize)

[[1.5 2.  3.  4. ]
 [4.  5.  6.  7. ]
 [8.  0.  9.  1. ]]
float64
8


In [35]:
import numpy as np

a =np.linspace(0, 2, 100)

print(a)

f=np.sin(a)
print("sin")
print(f)

[0.         0.02020202 0.04040404 0.06060606 0.08080808 0.1010101
 0.12121212 0.14141414 0.16161616 0.18181818 0.2020202  0.22222222
 0.24242424 0.26262626 0.28282828 0.3030303  0.32323232 0.34343434
 0.36363636 0.38383838 0.4040404  0.42424242 0.44444444 0.46464646
 0.48484848 0.50505051 0.52525253 0.54545455 0.56565657 0.58585859
 0.60606061 0.62626263 0.64646465 0.66666667 0.68686869 0.70707071
 0.72727273 0.74747475 0.76767677 0.78787879 0.80808081 0.82828283
 0.84848485 0.86868687 0.88888889 0.90909091 0.92929293 0.94949495
 0.96969697 0.98989899 1.01010101 1.03030303 1.05050505 1.07070707
 1.09090909 1.11111111 1.13131313 1.15151515 1.17171717 1.19191919
 1.21212121 1.23232323 1.25252525 1.27272727 1.29292929 1.31313131
 1.33333333 1.35353535 1.37373737 1.39393939 1.41414141 1.43434343
 1.45454545 1.47474747 1.49494949 1.51515152 1.53535354 1.55555556
 1.57575758 1.5959596  1.61616162 1.63636364 1.65656566 1.67676768
 1.6969697  1.71717172 1.73737374 1.75757576 1.77777778 1.79797

In [41]:
import numpy as np

a = np.array([[1,2],[5,4],[6,7]],order = 'C', subok=True)

print(a)

[[1 2]
 [5 4]
 [6 7]]


In [50]:
import numpy as np

x =np.array([[1,2],[3,4]], dtype =[('a','int32'),('b','int8')])

print(x['b'])

[[1 2]
 [3 4]]


In [53]:
 a = np.array(np.mat('1 2; 3 4'))
print(a)

[[1 2]
 [3 4]]


In [63]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [76]:
np.full((3,2),10,dtype='complex')

array([[10.+0.j, 10.+0.j],
       [10.+0.j, 10.+0.j],
       [10.+0.j, 10.+0.j]])