In [1]:
import numpy as np

a= np.arange(30)

b = a.reshape(10,3)
print("array is")

print(b)

print('\n')

print("transpose matrix")
s = b.T

print(s)

print("modified array is :")
for x in np.nditer(s):
    print(x)

array is
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


transpose matrix
[[ 0  3  6  9 12 15 18 21 24 27]
 [ 1  4  7 10 13 16 19 22 25 28]
 [ 2  5  8 11 14 17 20 23 26 29]]
modified array is :
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [3]:
#without using nditer

import numpy as np

arr = np.arange(12).reshape(3,4)

print("original array is",arr)

for rows in arr:
    for cells in rows:
        print(cells)

original array is [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11
