In [2]:
#modifying array values
import numpy as np

a=np.arange(12).reshape(3,4)

print("original array is",a)

for x in np.nditer(a,op_flags = ['readwrite']):
    x[...]=x*x 

print("modified array is",a)

original array is [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
modified array is [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
