In [1]:
#one dimensional array
import numpy as np

arr = np.array([1,2,3])

print (arr)

#more than one dimensional array

import numpy as md

mat = md.array([[5,3],[6,1],[3,2]])

print(mat)

#using ndmin

import numpy as md

mat = md.array([4,5,6,3,2],ndmin=0)

print(mat)

#for complex numbers

import numpy as md

comp = md.array([[4,5],[3,2]],dtype=complex)

print(comp)

[1 2 3]
[[5 3]
 [6 1]
 [3 2]]
[4 5 6 3 2]
[[4.+0.j 5.+0.j]
 [3.+0.j 2.+0.j]]
