In [2]:
#slicing

import numpy as np

arr  = np.arange(10)

s = arr[0:9:2] #s = slice (0,9,2)

print(s)

#array slicing

import numpy as np

arr = np.array([[1,2,4], [3,5,4], [8,6,7]])

print (arr[1:])

print("our array is")

print(arr)

print('\n')

print("when used elipsis")

print(arr[1,...]) #elipsis

print('\n')

[0 2 4 6 8]
[[3 5 4]
 [8 6 7]]
our array is
[[1 2 4]
 [3 5 4]
 [8 6 7]]


when used elipsis
[3 5 4]




In [40]:

import numpy as np

a = np.array([[11,22],[33,44 ],[55,66]])


x, y = a[:, :-1], a[:, -1]

print("x")
print(x)

print("y")
print(y)


x
[[11]
 [33]
 [55]]
y
[22 44 66]
