In [19]:
#vertical spliting 

import numpy as np

a = np.arange(0,60,2).reshape(15,2)
print("array is:",a)

print("vertical split:")
result = np.vsplit(a,5)
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])

array is: [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]
 [40 42]
 [44 46]
 [48 50]
 [52 54]
 [56 58]]
vertical split:
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[12 14]
 [16 18]
 [20 22]]
[[24 26]
 [28 30]
 [32 34]]
[[36 38]
 [40 42]
 [44 46]]
[[48 50]
 [52 54]
 [56 58]]


In [24]:
#Horizontal spliting
#spliting 

import numpy as np

a = np.arange(0,60,2).reshape(15,2)
print("array is:",a)

print("horizontal split:")
np.hsplit(a,2)



array is: [[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]
 [24 26]
 [28 30]
 [32 34]
 [36 38]
 [40 42]
 [44 46]
 [48 50]
 [52 54]
 [56 58]]
horizontal split:


[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16],
        [20],
        [24],
        [28],
        [32],
        [36],
        [40],
        [44],
        [48],
        [52],
        [56]]), array([[ 2],
        [ 6],
        [10],
        [14],
        [18],
        [22],
        [26],
        [30],
        [34],
        [38],
        [42],
        [46],
        [50],
        [54],
        [58]])]