In [6]:
#Array Manipulations and functions

import numpy as np

a= np.arange(6).reshape(3,2)
print("array a is",a)
print('\n')

b=np.arange(6,12).reshape(3,2)
print("array b is", b)

print("horizontal stacking")
print(np.hstack((a,b)))

print("\n")

print("vertical stacking")
print(np.vstack((a,b)))


array a is [[0 1]
 [2 3]
 [4 5]]


array b is [[ 6  7]
 [ 8  9]
 [10 11]]
horizontal stacking
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


vertical stacking
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
